### PR TITLE
Fix constrained optimizer documentation

### PR DESCRIPTION
**Pull request by rcurtin**
This solves #199. 

Our documentation for constrained functions is actually incorrect.  The documentation implies that both "hard" and "soft" constraints are supported but this is not true.  In fact, the augmented Lagrangian optimizer (the only constrained optimizer we currently have) requires "soft" (differentiable) constraints.  Although I think it would be useful to provide support for optimizers that can take in arbitrary constraints, at the moment we don't have any, so I thought it was best to just simplify the documentation.

Also I fixed an issue where the L-BFGS optimizer will return NaNs when the starting point gives a gradient that is 0.  Essentially, for some reason, we previously did not allow termination on the first iteration due to the gradient norm being too small.  That's likely just a code artifact; I can't find any good reason to avoid that.

### CODE REVIEW

**Comment by birm** [comment]
It looks like we need a corresponding mlpack pr to fix some dependent tests too?

**Comment by zoq** [comment]
> It looks like we need a corresponding mlpack pr to fix some dependent tests too?

This shouldn't break anything or require any update.

**Comment by rcurtin** [comment]
No, actually, it looks like mlpack's NCA implementation may depend on L-BFGS not terminating in the first iteration.  (I am not clear on why the memory checks or static code analysis jobs are failing...)

**Comment by zoq** [comment]
> I am not clear on why the memory checks or static code analysis jobs are failing...

I guess for the static analysis job we have to update the job config same we did for the mlpack one, will look into it now.

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
The static code analysis check works now.

**Comment by rcurtin** [comment]
Now that mlpack/mlpack#2479 is merged, this should build okay... let's find out...

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
@zoq the memory checks build times out, even after 6 hours, I think because it's trying to run *all* of the tests---do you think we should adapt the script in `jenkins-conf/memory/parse-tests.py` to the ensmallen codebase?  I am not familiar with that script, but I'm happy to give it a shot if you like. :+1:

**Comment by rcurtin** [comment]
Anyone willing to review this one?  I believe everything is working here and we could merge it. :+1:

**Comment by zoq** [comment]
> @zoq the memory checks build times out, even after 6 hours, I think because it's trying to run _all_ of the tests---do you think we should adapt the script in `jenkins-conf/memory/parse-tests.py` to the ensmallen codebase? I am not familiar with that script, but I'm happy to give it a shot if you like. 👍

I missed this one, I'll take a look at the memory script later, should be easy, but don't think we have to wait for the memory job to pass.

**Comment by zoq** [comment]
Just resolved the merge conflict.

**Pull request merged**
