### PR TITLE
Release version 2.14.0: "No Direction Home"

### PR DESCRIPTION
**Pull request by say4n**
This automatically-generated pull request adds the commits necessary to make the 2.14.0 release.

Once the PR is merged, mlpack-bot will tag the release as HEAD~1 (so that it doesn't include the new HISTORY block) and publish it.

Or, well, hopefully that will happen someday.

When you merge this PR, be sure to merge it using a *rebase*.

### Changelog

 * Add NSGA2 optimizer for multi-objective functions
    ([#149](https://github.com/mlpack/ensmallen/pull/149)).

 * Update automatic website update release script
   ([#207](https://github.com/mlpack/ensmallen/pull/207)).

 * Clarify and fix documentation for constrained optimizers
   ([#201](https://github.com/mlpack/ensmallen/pull/201)).

 * Fix L-BFGS convergence when starting from a minimum
   ([#201](https://github.com/mlpack/ensmallen/pull/201)).

### CODE REVIEW

**Comment by rcurtin** [comment]
I see that the generated description was wrong... let me take a look at the script to see if I can understand why.

**Comment by say4n** [comment]
Ah yes, I think we need to make the release script use the command agrs passed while grep-ing for the changelog string. Will I open an PR for it?

**Comment by rcurtin** [comment]
Actually, sure, if you want, we could close this, open a PR to fix the script, and then open a new release PR.  Up to you though; I'm happy to try this PR for a release too. :+1:

**Comment by say4n** [comment]
I can open a separate PR for the release script once this is merged. I think the offending line in the release script is [this](https://github.com/mlpack/ensmallen/blob/master/scripts/ensmallen-release.sh#L135).

**Comment by rcurtin** [comment]
Oh!  How did that get hardcoded there??  Oops...

**Comment by say4n** [comment]
Alright!

**Comment by say4n** [comment]
@rcurtin I have opened #215 to use the variables in the release script.

**Comment by rcurtin** [comment]
Thanks! :+1:

**Comment by say4n** [comment]
@zoq, will a release be added automatically post the CI build?

**Comment by rcurtin** [comment]
Actually mlpack-bot was supposed to do it but it looks like my Javascript must be incorrect:

```
16:52:03.370Z ERROR event: Cannot read property 'index' of null (id=f9ef4e80-dbf2-11ea-8996-2b32edfd1da1)
```

Anyway, I'll look into it shortly and finish mlpack-bot's job. :)

**Comment by say4n** [comment]
Ah! :)

**Pull request merged**
