### PR TITLE
Release version 2.17.0: "Pachis Din Me Pesa Double"

### PR DESCRIPTION
**Pull request by jonpsy**
This automatically-generated pull request adds the commits necessary to make the 2.17.0 release.

Once the PR is merged, mlpack-bot will tag the release as HEAD~1 (so that it doesn't include the new HISTORY block) and publish it.

Or, well, hopefully that will happen someday.

When you merge this PR, be sure to merge it using a *rebase*.

### Changelog

 * CheckArbitraryFunctionTypeAPI extended for MOO support ([#283](https://github.com/mlpack/ensmallen/pull/283)).

 * Refactor NSGA2 ([#263](https://github.com/mlpack/ensmallen/pull/263), [#304](https://github.com/mlpack/ensmallen/pull/304)).

 * Add Indicators for Multiobjective optimizers ([#285](https://github.com/mlpack/ensmallen/pull/285)).

 * Make Callback flexible for MultiObjective Optimizers ([#289](https://github.com/mlpack/ensmallen/pull/289)).

 * Add ZDT Test Suite ([#273](https://github.com/mlpack/ensmallen/pull/273)).

 * Add MOEA-D/DE Optimizer ([#269](https://github.com/mlpack/ensmallen/pull/269)).

 * Introduce Policy Methods for MOEA/D-DE ([#293](https://github.com/mlpack/ensmallen/pull/293)).

 * Add Das-Dennis weight initialization method ([#295](https://github.com/mlpack/ensmallen/pull/295)).

 * Add Dirichlet Weight Initialization ([#296](https://github.com/mlpack/ensmallen/pull/296)).

 * Improved installation and compilation instructions ([#300](https://github.com/mlpack/ensmallen/pull/300)).

 * Disable building the tests by default for faster installation ([#303](https://github.com/mlpack/ensmallen/pull/303)).

 * Modify matrix initialisation to take into account default element zeroing in Armadillo 10.5 ([#305](https://github.com/mlpack/ensmallen/pull/305)).

### CODE REVIEW

**Comment by jonpsy** [comment]
CC: #308 

"25 Din Mein Paisa Double" translates to "Money doubled in 25 days". A famous dialogue from the movie "Fir Hera Pheri". If you aren't already familiar with this meme, see [this video posted by Netfilx.](https://www.youtube.com/watch?v=0ew88RPjlK0&t=3s)

image

**Review by rcurtin — APPROVED** [review]
Awesome, this one looks like it has the right date. :+1:

**Review by zoq — APPROVED** [review]
Looks great to me.

**Review by coatless — APPROVED** [review]
Perfect! Thanks for learning about how to create ensmallen releases!

**Comment by coatless** [comment]
Huzzah! It's merged in. Thanks @rcurtin

**Comment by rcurtin** [comment]
But, it wasn't labeled `t: release`, so I have to do the release manually.  Ah well :smile:

**Pull request merged**
