### PR TITLE
ParallelSGD omp fix

### PR DESCRIPTION
**Pull request by zoq**
Fix for the test timeout seen here: http://ci.mlpack.org/view/ensmallen/job/docker%20ensmallen%20nightly%20build/

### CODE REVIEW

**Comment by zoq** [comment]
@coatless have seen your message in IRC, do you see a similar issue as described in https://github.com/mlpack/ensmallen/issues/132?

**Comment by coatless** [comment]
@zoq we're running a different set of checks than the official tests. So #132 didn't pop up.

**Comment by zoq** [comment]
I see, thanks for the clarification.

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Let's start the matrix build.

**Pull request merged**
