### PR TITLE
SPSA optimizer

### PR DESCRIPTION
**Pull request by zoq**
Implementation of the Simultaneous perturbation stochastic approximation (SPSA) method; An "Overview of the Simultaneous Perturbation Method for Efficient Optimization" by J. C. Spall.

### CODE REVIEW

**Comment by Rajiv2605** [comment]
@zoq Can I still work on this issue? Sorry for the late reply...

**Comment by zoq** [comment]
Sure, feel free to work on this one.

**Comment by Rajiv2605** [comment]
@zoq I have added the commits in the fork of this repo. Do I have to create a new PR or is there a way to reflect those changes in this PR itself?

**Comment by Rajiv2605** [comment]
@zoq I have created the PR #69 for SPSA implementation

**Comment by rcurtin** [comment]
We can continue in #69 then, so I'll go ahead and close this one.

**Pull request closed without merging**
