### PR TITLE
Swapped default params in AugLagrangian docs

### PR DESCRIPTION
**Pull request by matteosecli**

### CODE REVIEW

**Review by zoq — COMMENTED** [review]
Whoops, nice catch! Can you add the PR to the `HISTORY.md` file, there is already an entry `Fix typo in documentation (#270).` so if you can add the PR number to that entry that would be great.

**Comment by matteosecli** [comment]
> Whoops, nice catch! Can you add the PR to the `HISTORY.md` file, there is already an entry `Fix typo in documentation (#270).` so if you can add the PR number to that entry that would be great.

Sure, done! 🙂

**Review by zoq — APPROVED** [review]
Thanks no more comments from my side.

**Comment by zoq** [comment]
Thanks again for the contribution.

**Pull request merged**
