### PR TITLE
Callback idea

### PR DESCRIPTION
**Pull request by zoq**
Initial idea to handle callbacks, perhaps this is helpful to continue the discussion in https://github.com/mlpack/mlpack/issues/1481

### CODE REVIEW

**Comment by Rajiv2605** [comment]
Hi @zoq sorry for the late reply as I was stuck with my semester exams... Can I still work on completing this pr?

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Closing in favour of https://github.com/mlpack/ensmallen/pull/119.

**Comment by rcurtin** [comment]
Looks like we forgot to actually close it :)

**Pull request closed without merging**
