### PR TITLE
Release version 2.16.0: "Severely Dented Can Of Polyurethane"

### PR DESCRIPTION
**Pull request by rcurtin**
This automatically-generated pull request adds the commits necessary to make the 2.16.0 release.

Once the PR is merged, mlpack-bot will tag the release as HEAD~1 (so that it doesn't include the new HISTORY block) and publish it.

Or, well, hopefully that will happen someday.

When you merge this PR, be sure to merge it using a *rebase*.

### Changelog

 * Expand README with example installation and add simple example program showing usage of the L-BFGS optimizer ([#248](https://github.com/mlpack/ensmallen/pull/248)).

 * Refactor tests to increase stability and reduce random errors ([#249](https://github.com/mlpack/ensmallen/pull/249)).

### CODE REVIEW

**Comment by rcurtin** [comment]
Severely dented can in question:

IMG_20210211_180453

Hard to imagine what might have happened that this showed up on my doorstep like this... I guess I should just consider myself lucky it's still holding everything in...

**Comment by coatless** [comment]
But, but... your front step is missing a nice clear crystal gloss coating!

**Review by zoq — APPROVED** [review]
The release name is hilarious 👍

**Comment by ShikharJ** [comment]
Man, I laughed way too hard while reading the GitHub e-mail update.

**Pull request merged**
