### PR TITLE
Add version names and use Markdown links in HISTORY.md

### PR DESCRIPTION
**Pull request by rcurtin**
Addresses #122.  @coatless let me know if this is what you were thinking or if you had something else in mind. :)

### CODE REVIEW

**Comment by coatless** [comment]
@rcurtin perfect. Thank you.

**Comment by gauravk97** [comment]
Hi Gaurav here, from mlpack issue (https://github.com/mlpack/mlpack/issues/1974). I think in addition to the above changes, the following changes are also required: 
in file pso.hpp

  //! Retrieve value of impTolerance.
  size_t ImpTolerance() const { return impTolerance; }
  //! Modify value of impTolerance.
  size_t& ImpTolerance() { return impTolerance; }

here size_t -> double because impTolerance is of double datatype. Because of this, it was breaking in my system.

**Comment by rcurtin** [comment]
Yep, also needed is #126.  It'll be merged shortly and I'll do another release.  Sorry for the inconvenience.

**Comment by gauravk97** [comment]
@rcurtin I'm sorry for bugging you again and again :P but I have one more question and I hoped you could answer that for me. 
I am using the compiler gcc 8.3.0 while my friend was using gcc 5.4. And we both were building the mlpack library in our systems. In his system, this return type error didn't come up at all and the build executed perfectly even with ensmallen 1.16.0. I was curious how that happened.
Otherwise, with these fixes, even my build is now completing without issues. Thanks a lot. :)

**Comment by rcurtin** [comment]
@gauravk97 no worries---different versions of compilers will handle issues differently.  In earlier gcc's case, apparently it wasn't being strict about the return types because those functions aren't actually used in any of the code you're compiling.  Newer gcc is stricter (which I think is generally a good thing). :)

**Pull request merged**
