### PR TITLE
Implementation of saACM-ES

### PR DESCRIPTION
**Pull request by SuvarshaChennareddy**
This pull request is an initial implementation of saACM-ES, which is part of my Google Summer of Code (GSoC) project. Tests have not been added yet.

### CODE REVIEW

**Review by zoq — COMMENTED** [review]
Let me know if you want me to resolve the merge conflicts.

**Comment by SuvarshaChennareddy** [comment]
> Let me know if you want me to resolve the merge conflicts.

Thank you. However, I believe we should fully review the [implementation of IPOP-CMA-ES](https://github.com/mlpack/ensmallen/pull/373) before resolving the issues here. Is that fine?

**Comment by zoq** [comment]
100%

**Comment by SuvarshaChennareddy** [comment]
Can we keep this open? 

IPOP-CMAES still needs to be fully reviewed. As mentioned in its pull request, one of Demon SGD's tests keeps failing.

**Pull request closed without merging**
