### PR TITLE
bump check for min supported version of armadillo

### PR DESCRIPTION
**Pull request by conradsnicta**
followup to #318

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Looks good to me, let's do another release once this is merged.

**Review by rcurtin — APPROVED** [review]
Ahh, nice catch, I guess we forgot to update that check. :+1:

**Comment by coatless** [comment]
Always nice to see a willingness to bump minimum dependencies. Though, I think this is the second in under a year or two. Is this related to an upstream change in MLPACK?

**Comment by conradsnicta** [comment]
@coatless The bump was way back in 2021 via #318 (seems like a century ago). Unfortunately we missed updating the actual check for the version. This PR merely fixes the omission from 2021.

**Pull request merged**
