### PR TITLE
Doc fix

### LINKED ISSUE #290: Front() API
-->

#### Problem location

```doc/function_types.md```

#### Description of problem

The example is outdated, uses an older API. I'll do the change, but setting this issue as a reminder so that we don't sleep on it.

### PR DESCRIPTION
**Pull request by jonpsy**
#290

### CODE REVIEW

**Comment by jonpsy** [comment]
@zoq  I dont think HISTORY.md is necessary here.

**Review by zoq — APPROVED** [review]
Thanks :+1:

**Comment by zoq** [comment]
> @zoq I dont think HISTORY.md is necessary here.

No need, to update the file in this case.

**Review by birm — APPROVED** [review]

**Comment by zoq** [comment]
Thanks for the quick fix.

**Pull request merged**
