### PR TITLE
Release version 2.19.0: "Eight Ball Deluxe"

### PR DESCRIPTION
**Pull request by zoq**
This automatically-generated pull request adds the commits necessary to make the 2.19.0 release.

Once the PR is merged, mlpack-bot will tag the release as HEAD~1 (so that it doesn't include the new HISTORY block) and publish it.

Or, well, hopefully that will happen someday.

When you merge this PR, be sure to merge it using a *rebase*.

### Changelog

* Added DemonSGD and DemonAdam optimizers ([#211](https://github.com/mlpack/ensmallen/pull/211)).

 * Fix bug with Adam-like optimizers not resetting when `resetPolicy` is `true`. ([#340](https://github.com/mlpack/ensmallen/pull/340)).

 * Add Yogi optimizer ([#232](https://github.com/mlpack/ensmallen/pull/232)).

 * Add AdaBelief optimizer ([#233](https://github.com/mlpack/ensmallen/pull/233)).

 * Add AdaSqrt optimizer ([#234](https://github.com/mlpack/ensmallen/pull/234)).
   
 * Bump check for minimum supported version of Armadillo ([#342](https://github.com/mlpack/ensmallen/pull/342)).

### CODE REVIEW

**Review by conradsnicta — APPROVED** [review]

**Comment by conradsnicta** [comment]
@zoq @rcurtin the releases section on github still shows 2.18.2, as does ensmallen.org

**Comment by rcurtin** [comment]
Yeah!  I thought my scripts were bulletproof.  Or at least sort of robust.  Apparently not---I actually haven't managed to see anything useful in the logs.  I am actually traveling right now, so it may be a couple days until I can manage to debug this and figure out what's gone wrong.

**Comment by zoq** [comment]
I could do a manual release, but not sure that would be helpful in figuring out what the problem is.

**Comment by rcurtin** [comment]
I'm about to go out of internet service for probably a few days so it may be better to just do it manually, and I can sort out whatever the issue with mlpack-bot was when I get back.

**Comment by zoq** [comment]
Okay, I will do a manual release then.

**Comment by zoq** [comment]
Released on GitHub and updated the website as well.

**Pull request merged**
