### PR TITLE
AGEMOEA for Convex Fronts

### PR DESCRIPTION
**Pull request by IWNMWE**
This PR is to fix the drift seen in AGEMOEA for highly convex functions(eg MAF3)

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Looks good to me.

**Comment by IWNMWE** [comment]
> Looks good to me.

Still need to fix a few things.

**Comment by IWNMWE** [comment]
That's all the fixes I wanted to do. I think its good to go

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by IWNMWE** [comment]
[ensmallen_tests.global.DemonSGDLogisticRegressionTest] Looks like this test might be  failing due to rng seed

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Same here, let's see if that comes back green and merge it.

**Comment by IWNMWE** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
@mlpack-jenkins test this please

**Comment by zoq** [comment]
Thanks for the contribution.

**Pull request merged**
