### PR TITLE
Remove unused `const` to fix compilation warnings

### PR DESCRIPTION
**Pull request by rcurtin**
Another pretty simple PR.  It should fix many warnings that I see when I compile mlpack.

### CODE REVIEW

**Review by birm — APPROVED** [review]
Do you think this needs a history entry?

**Comment by rcurtin** [comment]
Agreed, the changelog entry should fix the Travis build too.

**Comment by rcurtin** [comment]
@mlpack-jenkins test this please

**Comment by rcurtin** [comment]
The memory checks timed out, but it looks like there were no errors.  I'll go ahead and merge. :+1:

**Pull request merged**
