### PR TITLE
Update release scripts

### PR DESCRIPTION
**Pull request by rcurtin**
I noticed in #185 that @favre49 wasn't able to push any extra commits during merge, and I ended up with a better understanding of Github branch protection permissions.  Anyway, what it means is that folks in the Contributors team can't push directly to `master` (and now, neither can I, I shouldn't have been able to to begin with given my propensity for typing before thinking :smile:), and so the release scripts have to be updated.

Here's the new idea for the workflow:

1. Anyone (actually even including folks not on the Contributors team) can run the `scripts/ensmallen-release.sh` script, like this:

```
$ scripts/ensmallen-release.sh rcurtin 2 13 0 "New Release Name"
```

(The Github username is necessary so that it's known where the fork is.)  This script will create a new branch in the given user's fork (i.e., `rcurtin/ensmallen:release-2.13.0` in the example), and automatically open a PR for that release.  The PR will actually include one *extra* commit to create a new HISTORY block.  These PRs will look exactly like this: #191 and will be tagged `t: release`.

2. Once that PR is approved and merged, @mlpack-bot will tag the release and automatically push a new release to Github.  @mlpack-bot will also run the `update-website-after-release.sh` script to push any changes to the website (which is then rebuilt and deployed by Jenkins).

Anyway, this is a much easier and more automatic process than before.  I wonder if I should make a *second* bot so we can quickly and automatically get two reviews for these automatic PRs, but maybe having a human do sanity checks here isn't a bad thing.  It shouldn't take more than 30 seconds to review anyway. :)  (I do think that I'll have mlpack-bot automatically approve immediately if the PR was opened by someone on the Contributors team.)

I still have some amount of homework to do: I need to implement the mlpack-bot code.  But since I don't want to release over and over and over again while I debug, I'll just do it iteratively, and each time it fails I'll just do the `git tag` and `update-website-after-release.sh` myself, which is easy enough.

### CODE REVIEW

**Comment by birm** [comment]
I've been occasionally updating [homebrew-core's ensmallen formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ensmallen.rb) and it sure would be nice if we had a way to automate that too.

**Comment by coatless** [comment]
Maybe a GitHub action?

https://github.com/marketplace/actions/bump-homebrew-formula

**Comment by rcurtin** [comment]
Hmm, I wonder if we can leave mlpack-bot out of the loop here and instead use Github Actions to do the release.  I'll look into it, but I'm unclear on whether the time I've already put into learning octokit via probot would let me put together mlpack-bot to do that faster. :smile:

**Comment by rcurtin** [comment]
Ok, I'll merge this now and we can see what happens next release... :)

**Pull request merged**
