### PR TITLE
Typo in LBFGS() method of AugLagrangian

### PR DESCRIPTION
**Pull request by matteosecli**

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Nice catch!

**Review by rcurtin — APPROVED** [review]
Agreed, thank you for the fix!  I'll add a changelog entry during merge.

**Comment by rcurtin** [comment]
Blah, I fubar'ed the merge a little bit, sorry about that.  After merging to master it should be fine though (I'll do that once the builds pass).

**Comment by rcurtin** [comment]
Thanks @matteosecli! :+1:

**Comment by matteosecli** [comment]
@rcurtin you're welcome! 😃 

That's a great lib btw, thank you all! 🥇

**Pull request merged**
